---
title: "Nate Posner"
format:
  html:
    theme: litera
    embed-resources: true
---

# Practice Activity: Text Data - Spam Emails

In this activity you'll work with a small sample from the [Enron email corpus](https://en.wikipedia.org/wiki/Enron_Corpus). The [data set we'll use](https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv) contains the subjects and bodies of a sample of e-mails that the Federal Energy Regulatory Commission (FERC) collected during their 2002 investigation of the energy company [Enron](https://en.wikipedia.org/wiki/Enron). Each row in the data set is an email and there are three columns

- subject: the subject of the email
- body: the text of the email
- spam: spam indicator, 1 if spam, 0 if not

For this activity we will only consider the body of the emails (though you could also include the subject using similar methods).

1\. The corpus is the body column in the [data set](https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv); read this column in to create the corpus.

In [1]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS

In [2]:
import pandas as pd
import requests

In [3]:
emails = pd.read_csv('https://raw.githubusercontent.com/kevindavisross/data301/refs/heads/main/data/enron_email.csv')
corpus = emails[['body']].copy()
corpus

                                                   body
0     we invoiced mirant americas for deal 705989 an...
1     because the payback was done for october 2001 ...
2     for december 1999 , since the volumes for tran...
3     i would think that the first contract should g...
4     welcome to the aol instant messenger ( sm ) se...
...                                                 ...
1985  simply visti our site and let ' s see if we ca...
1986  order your medication here - no doctor visit n...
1987  wed , 09 jun 2004 13 : 33 : 18 - 0300\nsir or ...
1988  had chance at last to view the warner bros . l...
1989  while example milk . water , own , make , wire...

[1990 rows x 1 columns]

2\. Describe in words in detail the steps that you would take to clean the emails and create the term-frequency matrix. We will write the code in the next part, but think carefully first about the process: how do we turn this text into tabular data?

**I would first make all the words lowercase and remove special characters so that the data isn't skewed. Then, I would count each instance of each word and arrange the counts into a table or matrix to see the counts of each word in each email.**

3\. Use `CountVectorizer` to create the TF matrix, and then convert it to a pandas data frame with appropriate column names. You can just use the defaults in `CountVectorizer`. Hint: this should pretty much be a straight copy of code from the reading, but make sure you understand the process behind the code.

In [4]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
from sklearn.feature_extraction.text import CountVectorizer
emails = emails.dropna(subset=['body'])
corpus = emails['body']

In [5]:
vec = CountVectorizer()
vec.fit(corpus)
tf_sparse = vec.transform(corpus)

In [6]:
tf = pd.DataFrame(
    tf_sparse.todense(),
    columns=vec.get_feature_names_out(),
    index=corpus.index
)
tf

,00,000,0000,000000,000000000002858,000000000049773,000080,0001,00020608,0004,...,zyban,zykfe,zyl,zynsdirnh,zynve,zyqtaqlt,zyyqywp,zzezrjok,zzo,zzso
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

4\. Explain what a document frequency (DF) is, and the idea of an IDF. Why might we use TF-IDF rather than just TF? This question is asking about concepts rather than computations.

**TF (term frequency) measures how much a term appears within a specific document.**

**DF (document frequency) measures how much a term appears across different documents, whereas IDF is a weight that makes words that only appear in less documents be a higher weight.**

**Using TF-IDF is useful because it weighs words based on their inter-document frequency vs. intra-document frequency, which can help us understand the importance of a word (basically, weighting words like "the" less and weighting certain keywords with high frequency in some documents higher).**

5\. Use `TfidfVectorizer` to create the TF matrix, and then convert it to a pandas data frame with appropriate column names. You can just use the defaults in `TfidfVectorizer`. Hint: this should pretty much be a straight copy of code from the reading, but make sure you understand the process behind the code.

In [7]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
vec_tfidf = TfidfVectorizer()
vec_tfidf.fit(corpus)
tfidf_sparse = vec_tfidf.transform(corpus)

In [9]:
tfidf = pd.DataFrame(
    tfidf_sparse.todense(),
    columns=vec_tfidf.get_feature_names_out(),
    index=corpus.index
)
tfidf

,00,000,0000,000000,000000000002858,000000000049773,000080,0001,00020608,0004,...,zyban,zykfe,zyl,zynsdirnh,zynve,zyqtaqlt,zyyqywp,zzezrjok,zzo,zzso
0,0.0,0.106273,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,0.0,0.096680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.116092,0.0
1986,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1987,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1988,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1989,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

6\. Remember that the data set also contains an indicator of whether or not the email is spam. In this part you will use descriptive statistics and plots to compare the spam and non-spam emails in terms of their text, represented by the TF and TF-IDF matrices. This part is pretty open ended. First brainstorm some questions or things to investigate, and then write the code to produce relevant summaries.

Note: there are 10 emails for which the spam indicator is missing. You should remove them for this part. We'll come back to them soon.

**I'm going to investigate:**

**- If spam emails contain certain vocabulary as opposed to others**

**- Length of spam vs not spam emails**

**- Most common words in spam vs not spam**

In [10]:
tenemails = emails[emails['spam'].notna()]
tf_tenemails = tf.loc[tenemails.index]
tfidf_tenemails = tfidf.loc[tenemails.index]

**If spam emails contain certain vocabulary as opposed to others**

In [11]:
keywords = ["free", "click", "now", "money", "credit", "limited",
                 "buy", "cash", "offer", "guarantee", "viagra", "winner"]

In [12]:
keywords_tf = tf_tenemails[keywords]

In [30]:
contains_word = (keywords_tf > 0)
percent_by_group = contains_word.groupby(tenemails['spam']).mean() * 100
percent_by_group

,free,click,now,money,credit,limited,buy,cash,offer,guarantee,viagra,winner
spam,,,,,,,,,,,,
0.0,2.920443,2.719033,7.150050,1.409869,0.906344,0.906344,1.812689,1.309164,1.711984,0.000000,0.000000,0.000000
1.0,14.254860,15.766739,17.602592,12.850972,4.427646,6.803456,5.075594,4.427646,10.799136,3.779698,5.075594,0.539957

**Length of spam vs not spam emails**

In [ ]:
email_length = tf_tenemails.sum(axis=1)
email_length.groupby(tenemails['spam']).describe()

      count        mean         std  min   25%   50%    75%     max
spam
0.0   993.0  135.600201  181.695344  2.0  28.0  74.0  175.0  1833.0
1.0   926.0  187.415767  276.038679  0.0  41.0  81.0  193.5  2594.0

**Most common words in spam vs not spam**

In [ ]:
word_totals = tf_tenemails.groupby(tenemails['spam']).sum()
top_spam_words = word_totals.loc[1.0].sort_values(ascending=False).head(10)
top_spam_words

the     4815
to      3472
and     3344
of      3038
in      2064
you     1827
for     1653
this    1536
is      1447
your    1215
Name: 1.0, dtype: int64

In [ ]:
top_norm_words = word_totals.loc[0.0].sort_values(ascending=False).head(10)
top_norm_words

the      4772
to       3939
ect      3616
and      1941
hou      1904
for      1866
enron    1601
on       1540
of       1461
this     1294
Name: 0.0, dtype: int64

7\. Now consider the 10 emails for which the true spam status is unknown. How might you decide if each email is spam or not? Brainstorm some ideas before proceeding. How can you use the TF and TF-IDF matrices for emails with known spam status?

**I could use the TF and TF-IDF matricies from the emails with known spam status (especially the first of the three tests I did) to see if the 10 unknown emails share characteristics with spam or non-spam emails. I could also look at their overall length and keywords from the last test to further narrow down my ideas.**

8\. Consider just one email with unknown spam status, with `loc` 1980. Compute the cosine distance between the TF representation of this email and the TF representation of each of the emails with known spam status.

In [38]:
from sklearn.metrics import pairwise_distances

In [39]:
unknown_tf = tf.loc[[1980]]
tf_distances = pairwise_distances(unknown_tf, tf_tenemails, metric="cosine")[0]
tf_distances = pd.Series(tf_distances, index=tf_tenemails.index)
tf_distances

0       0.736928
1       0.542990
2       0.775802
3       0.653954
4       0.519088
          ...
1975    0.944996
1976    0.649040
1977    0.448669
1978    0.693219
1979    0.931826
Length: 1919, dtype: float64

9\. Sort the results of the previous part to examine the emails with known spam status that are most similar to the unknown email. If you had to determine if the unknown email was spam or not, which would you pick and why?

In [40]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
tf_sorted = tf_distances.sort_values()
tf_sorted.head(10)

1889    0.393060
1032    0.398488
1376    0.408606
714     0.414644
1110    0.415807
26      0.418573
180     0.423172
879     0.424620
713     0.427930
139     0.434841
dtype: float64

In [41]:
tenemails.loc[tf_sorted.head(10).index, 'spam']

1889    1.0
1032    1.0
1376    1.0
714     0.0
1110    1.0
26      0.0
180     0.0
879     0.0
713     0.0
139     0.0
Name: spam, dtype: float64

10\. Repeat the two previous parts using TF-IDF instead of TF. Do the results change?

In [42]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
unknown_tfidf = tfidf.loc[[1980]]
tfidf_distances = pairwise_distances(unknown_tfidf, tfidf_tenemails, metric="cosine")[0]
tfidf_distances = pd.Series(tfidf_distances, index=tfidf_tenemails.index)

In [43]:
tfidf_sorted = tfidf_distances.sort_values()
tfidf_sorted.head(10)

1032    0.758668
1977    0.784122
48      0.790062
1689    0.793425
1796    0.798005
180     0.800402
586     0.801481
1376    0.802614
279     0.802654
718     0.803812
dtype: float64

In [44]:
tenemails.loc[tfidf_sorted.head(10).index, 'spam']

1032    1.0
1977    1.0
48      0.0
1689    1.0
1796    1.0
180     0.0
586     0.0
1376    1.0
279     0.0
718     0.0
Name: spam, dtype: float64

11\. Now proceed in a similar manner to "guess" the spam status of each of the unknown emails.

In [45]:
# ENTER YOUR CODE HERE. FEEL FREE TO ADD CELLS
unknown_emails = emails[emails['spam'].isna()]
tfidf_unknown = tfidf.loc[unknown_emails.index]

In [46]:
all_distances = pairwise_distances(tfidf_unknown, tfidf_tenemails, metric="cosine")
all_distances = pd.DataFrame(all_distances, index=unknown_emails.index, columns=tfidf_tenemails.index)

In [47]:
def majority_vote(row):
    nearest_5 = row.sort_values().head(5).index
    return tenemails.loc[nearest_5, 'spam'].mean()

In [48]:
vote_share = all_distances.apply(majority_vote, axis=1)
guesses = (vote_share > 0.5).astype(int)
guesses

1980    1
1981    0
1982    0
1983    0
1984    0
1985    1
1986    1
1987    1
1988    1
1989    0
dtype: int64